server:
    port: 80
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testsl?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: tomkluas
        #password: root

    jpa:
      hibernate:
        ddl-auto: update
